feat: added correct lanes
cultuurnet/uitpas-mobile-app pull request #161
Opened 2023-04-06 10:59 UTC by JasperVercammen

2023-04-06 13:36 UTC, samvanhoeyicapps requested changes

2023-04-06 13:36 UTC, samvanhoeyicapps commented on src/shop/Shop.tsx
>        <RewardsSection filter="online" title={t('SHOP.SECTIONS.ONLINE')} />
van mij mag dit nu ook wel een lanes object zijn, waar over gemapped wordt

2023-04-06 13:43 UTC, JasperVercammen commented on src/shop/Shop.tsx
>        <RewardsSection filter="online" title={t('SHOP.SECTIONS.ONLINE')} />
Dekke toch, ik dacht het ook al, maar was te lui.. Will fix!

2023-04-07 11:28 UTC, samvanhoeyicapps submitted a review, later dismissed

2023-04-07 11:52 UTC, samvanhoeyicapps approved these changes

2023-04-07 11:54 UTC, merged