fix: allow array params as query params
cultuurnet/uitpas-mobile-app pull request #177
Opened 2023-04-19 14:52 UTC by JasperVercammen

2023-04-20 08:29 UTC, samvanhoeyicapps requested changes

2023-04-20 08:33 UTC, samvanhoeyicapps commented on src/_http/HttpClient.ts
>        for (const property in params) {
(const [key, value] of Object.entries(params)) dit is misschien ook mooier

2023-04-20 09:06 UTC, JasperVercammen commented on src/_http/HttpClient.ts
>          if (params[property] !== null && params[property] !== undefined) {
Eik

2023-04-21 12:01 UTC, samvanhoeyicapps commented on src/_http/HttpClient.ts
>          if (params[property] !== null && params[property] !== undefined) {
clean

2023-04-25 05:46 UTC, samvanhoeyicapps approved these changes

2023-04-25 06:50 UTC, merged