Family overview
cultuurnet/uitpas-mobile-app pull request #290
Opened 2023-11-15 10:04 UTC by chennara

2023-11-15 15:13 UTC, samvanhoeyicapps requested changes

2023-11-15 15:13 UTC, samvanhoeyicapps commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +  const formItems = useMemo(() => {
is this necessary? I think you can do the check inline instead of in a separate function, then the enum is also not necessary

2023-11-15 15:13 UTC, samvanhoeyicapps commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +            familyMembers?.filter(({ mainFamilyMember }) => !mainFamilyMember).length > 0
```suggestion
            familyMembers?.length > 1
```

2023-11-15 15:13 UTC, samvanhoeyicapps commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +        renderItem={({ item: formItem }) => {
```suggestion
        renderItem={({ item: familyMember }) => {
```

2023-11-15 15:13 UTC, samvanhoeyicapps commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +          if (formItem.type === TFormItemType.FamilyMemberItem) {
```suggestion
          if (familyMember.mainFamilyMember) {
```

2023-11-15 15:13 UTC, samvanhoeyicapps commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +          } else {
this could also be if(familyMembers.length % 2 === 0)

2023-11-16 08:22 UTC, chennara commented on src/_assets/images/avatars/getAvatarByNameOrDefault.ts
> +export const getAvatarByNameOrDefault = (name: string) => {
Moved to `utils`

2023-11-16 08:25 UTC, chennara commented on src/onboarding/family/familyOverview/FamilyOverview.tsx
> +          if (formItem.type === TFormItemType.FamilyMemberItem) {
This will break typing.

2023-11-17 09:38 UTC, samvanhoeyicapps approved these changes

2023-11-17 09:38 UTC, merged