Family member rewards
cultuurnet/uitpas-mobile-app pull request #317
Opened 2023-11-27 13:24 UTC by chennara

2023-11-29 09:03 UTC, samvanhoeyicapps requested changes

2023-11-30 09:42 UTC, chennara commented on src/_components/family/familyMemberPoints/FamilyMemberPoints.tsx
> +  RightComponent: ({ familyMember }: { familyMember: TFamilyMember }) => ReactElement;
Yes 👌🏼. Is this not a convention?

2023-11-30 09:46 UTC, chennara commented on src/shopDetail/ShopDetail.tsx
> +  const [familyMembersSectionOffset, setFamilyMemberSectionOffset] = useState(0);
Yes, I don't think we are able to calculate this value on the fly, since the value gets updated in `onLayout` callbacks.

2023-11-30 09:56 UTC, chennara commented on src/shopDetail/ShopDetail.tsx
> +                const stickyOffset = 48 + 16;
I've added a comment in the code explaining the value.

2023-11-30 10:47 UTC, samvanhoeyicapps commented on src/shopDetail/ShopDetail.tsx
> +                const stickyOffset = 48 + 16; // This equals the area height of the redeem button, which equals the button height (48) + margin (16)
could you put them in a const and reuse it here? So when they get changed, this also gets updated.

2023-11-30 16:09 UTC, samvanhoeyicapps approved these changes

2023-11-30 16:09 UTC, merged