UIT-55: Add ProfileNotFound page when no passholder is linked to your account
cultuurnet/uitpas-mobile-app pull request #41
Opened 2022-11-17 09:38 UTC by hstandaert

![ezgif-3-67c5458f97](https://user-images.githubusercontent.com/4415097/202410525-8509bbb0-f384-4b63-8023-7d3141b26d7c.gif)

2022-11-17 13:42 UTC, samvanhoeyicapps requested changes

2022-11-17 13:42 UTC, samvanhoeyicapps commented on src/_components/checkbox/Checkbox.tsx
> +const Checkbox: FC<TProps> = ({ isChecked, onChange, name, label, checkedColor = 'turqoise', iconSize, ...props }) => {
typfoutje? turqoise --> turquoise

2022-11-18 08:35 UTC, hstandaert commented on src/profile/_queries/useGetMe.ts
> +    retry: (_, error) => {
Dat wordt onderliggend doorgegeven aan react-query he ;-) Maar da's redelijk specifiek voor die passholders call, dus daarom in deze query zelf gedefinieerd.

2022-11-18 09:19 UTC, samvanhoeyicapps commented on src/_components/bulletList/BulletListItem.tsx
> +
enter?

2022-11-18 09:53 UTC, samvanhoeyicapps approved these changes

2022-11-18 10:32 UTC, merged